### ISSUE TITLE
Polylines

### ISSUE THREAD

**Issue by mikeantonacci** [rectangle-dbmi/PATTrack-Windows#2]
We still need to get, store and sort the patterns to create and draw the polylines just like in the Android app.

**Comment by mikeantonacci** [comment]
Looks like there's no longer a need to sort the patterns, PAT fixed this on their end.  We might still have to store these to minimize data usage...

**Comment by epicstar** [comment]
XD Looks like I can fix it on my end eventually too

**Comment by epicstar** [comment]
Polylines here and done
